services:
  - type: web
    name: statpulse-public
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y \
        libgtk-4-1 \
        libgraphene-1.0-0 \
        libgstreamer-gl1.0-0 \
        libgstreamer-plugins-bad1.0-0 \
        libavif15 \
        libenchant-2-2 \
        libsecret-1-0 \
        libmanette-0.2-0 \
        libgles2-mesa \
      && pip install -r requirements.txt && \
      playwright install
    startCommand: gunicorn app.main:app
    plan: standard
    autoDeploy: true
